### ISSUE TITLE
Possible corner case while bucketing

### ISSUE THREAD

**Issue by k3yavi** [10XGenomics/rust-pseudoaligner#4]
Hi guys,

I think [this](https://github.com/10XGenomics/rust-pseudoaligner/blob/master/src/build_index.rs#L190) line can be modified to the following:
```
    if slice_start > 0 || (data.len() - slice_start) > min_size {
```

I am imagining a case where everything fall into one bucket then the variable `slice_start` will never increase and result in an empty result.

**Comment by pmarks** [comment]
Yes, looks like there was a bug. Fixed w/ test in #10.
